(defun sweyla927240 ()
  "Theme generated by Sweyla: http://sweyla.com/themes/seed/927240/"
  (interactive)
  (color-theme-install
   '(sweyla927240
     ((background-color . "#000002")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#AC3F2B"))))
     (font-lock-constant-face ((t (:foreground "#901A8A"))))
     (font-lock-builtin-face ((t (:foreground "#5D6D50"))))
     (font-lock-function-name-face ((t (:foreground "#5D6B66"))))
     (font-lock-variable-name-face ((t (:foreground "#342B9C"))))
     (font-lock-keyword-face ((t (:foreground "#1A943A"))))
     (font-lock-string-face ((t (:foreground "#6E6416"))))
     (font-lock-doc-string-face ((t (:foreground "#6E6416"))))
     (font-lock-type-face ((t (:foreground "#FF1B0C"))))
     )))

(provide 'sweyla927240)
